name: Add Review Labels

on:
  pull_request:
    types: [ labeled ]

permissions:
  pull-requests: write
  contents: write

jobs:
  add_reviewer_labels:
    if: ${{ github.event.label.name == 'reviewers-needed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: |
          cat $GITHUB_EVENT_PATH
      - name: Add Labels
        run: |
          gh pr edit $PR_NUMBER -R mpi/gha-playground --add-label "team-1,team-2" --remove-label "reviewers-needed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_REPO: ${{ github.event.repository.git_url }}