name: Add Review Labels

on:
  pull_request:
    types: [ labeled ]

permissions:
  pull-requests: write
  contents: write

jobs:
  add_reviewer_labels:
    if: ${{ github.event.label.name == 'reviewers-needed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add Labels
        run: |
          gh pr edit --add-label "team-1,team-2" --remove-label "reviewers-needed"
