name: Add Review Labels

on:
  pull_request:
    types: [ labeled ]

permissions:
  pull-requests: write
  contents: write

env:
  TEAMS: |
    team-1
    team-2
    team-3
  REVIEWERS: 2

jobs:
  add_reviewer_labels:
    if: ${{ github.event.label.name == 'reviewers-needed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: |
          cat $GITHUB_EVENT_PATH
      - name: Print Existing Labels
        run: |
          echo "$LABELS"
        env:
          LABELS: |
            ${{ join(github.event.pull_request.labels.*.name, '
            ') }}
      - name: Calculate Reviewer Labels
        id: calculate_labels
        run: |
          REMAINING_LABELS=$(comm -23 <(echo "$TEAMS" | sort) <(echo "$LABELS" | sort) | shuf)
          echo -e "$LABELS\n$REMAINING_LABELS" | head -n $REVIEWERS | paste -sd ',' | xargs -I {} echo "::set-output name=labels::{}"
        env:
          LABELS: |
            ${{ join(github.event.pull_request.labels.*.name, '
            ') }}
      - name: Print Reviewer Labels
        run: |
          echo "Labels: $LABELS"
        env:
          LABELS: ${{ steps.calculate_labels.outputs.labels }}
      - name: Udpdate Labels
        run: |
          gh pr edit $PR_NUM -R $GITHUB_REPOSITORY --add-label "$LABELS" --remove-label "reviewers-needed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.pull_request.number }}
          LABELS: ${{ steps.calculate_labels.outputs.labels }}