name: Normalize NPM repository
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
#  types: [opened, reopened]
jobs:
  normalize_repo:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Fix repository URL
        run: date +%s > repository.txt
      - name: Commit changes
        run: |
          git add repository.txt
          git commit --amend --no-edit || echo "No changes to commit."
          git push --force-with-lease

#git config --global user.name 'dependabot[bot]'
#git config --global user.email 'dependabot[bot]@users.noreply.github.com'
#git commit -am "Adjust repository" || echo "No changes to commit."
#git push
