name: Normalize NPM repository
on:
  pull_request:
    types: [ opened, reopened ]
    paths:
      - '**package-lock.json'
permissions:
  pull-requests: write
  contents: write

jobs:
  normalize_repo:
    if: startsWith(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Fix repository URL
        run: |
          sed -i -e 's/resolved": "https:\/\/registry.npmjs.org/resolved": "https:\/\/custom.registry/g' package-lock.json
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add repository.txt
          git commit -am "Adjust npm repository url"
          git push
