name: Normalize NPM repository
on:
  pull_request:
    types: [opened, reopened]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix repository URL
        run: date +%s > repository.txt
      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add repository.txt
          git commit -am "Adjusted repository URL"
          git push