name: Normalize NPM repository
on:
  pull_request:
    types: [opened, reopened]
jobs:
  normalize_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Fix repository URL
        run: date +%s > repository.txt
      - name: Commit changes
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git add repository.txt
          git commit -am "Adjusted repository URL" || echo "No changes to commit."
          git push